version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: db
      DATABASE_USER: hackaton
      DATABASE_PASSWORD: qwerty123
      DATABASE_NAME: uber_db
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: hackaton
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_DB: uber_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  test:
    build: .
    environment:
      DATABASE_HOST: db
      DATABASE_USER: hackaton
      DATABASE_PASSWORD: qwerty123
      DATABASE_NAME: uber_db
    depends_on:
      - db
    command: npm run test

volumes:
  postgres_data:
